import { AxiomWebVitals } from 'next-axiom';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <AxiomWebVitals />
      <body>{children}</body>
    </html>
  );
}
